"""add foreign key to onboarding

Revision ID: 572b050fe1f0
Revises: 140960c12de3
Create Date: 2024-06-29 12:29:51.431147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '572b050fe1f0'
down_revision = '140960c12de3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboardings', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_onboardings_employee_id_employees'), 'onboardings', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_onboardings_employee_id_employees'), 'onboardings', type_='foreignkey')
    op.drop_column('onboardings', 'employee_id')
    # ### end Alembic commands ###
